Lesson 3
jolie-piliutsik/homework pull request #1
Opened 2020-08-02 18:23 UTC by jolie-piliutsik

add files task 2

2020-08-03 10:57 UTC, alka1ra requested changes
просьба доработать код и учесть все написанные замечания.

2020-08-03 10:57 UTC, alka1ra commented on src/task2/Atm.java
> +    public int clientCash = 2330; //сумма денег, которую хочет снять клиент
сумма денег,которую хочет снять клиент, не должна быть уже определена в классе банкомата, потому что она может изменяться. соответственно,она приходит извне - её нужно передавать в метод withdrawMoney в качестве параметра из места.
также она не характеризует внутреннее состояние банкомата и не должна быть полем класса - это значит, что принцип инкапсуляции нарушен.

2020-08-03 10:57 UTC, alka1ra commented on src/task2/Atm.java
> +    public void addCashToAtm() {
реализация метода не соответствует его названию. метод говорит "добавь деньги в банкомат" - а откуда берутся эти деньги? они приходят снаружи (должны приходить, по крайней мере).
в данном же случае метод просто печатает количество денег внутри банкомата.

а снаружи мы не можем добавить деньги, т.е. вызвать метод банкомата из main и сказать ему - добавь к существующим внутри тебя деньгам в себя столько-то 20-ок, столько-то 50-ок,столько-то 100-ок.

что переделать: привести метод в соответствие своему названию,т.е. реализовать возможность добавления денег извне в банкомат.

2020-08-03 10:57 UTC, alka1ra commented on src/task2/Atm.java
> +    int numberOf20 = (clientCash - (numberOf50 * 100) - (numberOf50 * 50)) / 20; //количество купюр номиналом 20
код реализован не в методе, а внутри класса. это значит, что код выполнится один раз при создании объекта класса - и больше выполняться не будет для каждого конкретного объекта.

вывод - нужно внести этот код в соответствующий метод для возможности его вызова и повторного выполнения.

2020-08-03 10:57 UTC, alka1ra commented on src/task2/Atm.java
> +    public void SuccessfulOperation() {
названия методов пишутся с маленькой буквы.

2020-08-03 10:57 UTC, alka1ra commented on src/task2/Atm.java
> +    public void SuccessfulOperation() {
непонятно, что это за успешная операция? к чему она относится?

2020-08-03 10:57 UTC, alka1ra commented on src/task2/Atm.java
> +    public void withdrawMoney() {
вынести переменную clientCash из класса,а приходить в метод она должна в качестве параметра: withdrawMoney(clientCash)

2020-08-03 10:57 UTC, alka1ra commented on src/task2/Atm.java
> +    public void withdrawMoney() {
также метод может возвращать булевское значение об успешности проведенной операции. т.е. метод successfullOperation не нужен.

2020-08-03 10:57 UTC, alka1ra commented on src/task2/Atm.java
> +    public void SuccessfulOperation() {
также этот метод назван неправильно - здесь используется прилагательное+существительное. но название метода всегда должно начинаться с глагола.
суть любого метода в том,что он олицетворяет действие. действие в обычном, человеческом, языке представлено глаголом.  как я могу сделать "успешная операция"? 
лучше сделать "являюсь успешной операцией", т.е. isSuccessfulOperation.

2020-08-04 15:59 UTC, alka1ra requested changes

2020-08-04 15:59 UTC, alka1ra commented on src/task1/Main.java
> +        boolean compareTwoObjects = time1.calculateSeconds() > time2.calculateSeconds();
сравнение объектов нужно было сделать не в мэйне,а в отдельном методе класса Time, который называется equals (стандартное название метода сравнения в джаве) и принимает в себя другой объект, с которым нужно произвести сравнение

2020-08-04 15:59 UTC, alka1ra commented on src/task1/Main.java
> +        Time time1 = new Time(2, 75, 1000);
разделение времени на часы,минуты и секунды подразумевает, что количество секунд,переданное в метод,не будет превышать 60 (сколько есть в минуте). поэтому стоит добавить проверку на значение переданного параметра с выводом ошибки либо разбитием переданного числа в часы,минуты и секунды.

2020-08-04 15:59 UTC, alka1ra commented on src/task1/Main.java
> +        Time time2 = new Time(3, 71, 10);
то же самое, что я писала о секундах,можно сказать и о минутах: не пишется время 3 часа 71 минута, а пишется 4 часа 11 минут

2020-08-04 15:59 UTC, alka1ra commented on src/task1/Time.java
> +    public int allSec;
параметр лишний (дублирует предыдущие), все секунды можно получать в методе calculateSeconds, который из часов,минут и секунд, находящихся в классе, вычисляет общее количество секунд

2020-08-04 15:59 UTC, alka1ra commented on src/task1/Time.java
> +    }
ненужные методы - это дубляж функционала getHours, getMinutes, getSeconds, которые возвращают значения полей объекта

2020-08-04 15:59 UTC, alka1ra commented on src/task1/Time.java
> +
добавить метод equals (переопределить метод equals класса Object)

2020-08-07 19:19 UTC, Yauhenda commented on src/task1/Time.java
> +import com.sun.deploy.association.Action;
по-моему этот импорт не используется в классе

2020-08-27 06:40 UTC, alka1ra requested changes

2020-08-27 06:40 UTC, alka1ra commented on src/taskAirline/Airline.java
> +    public String dayOfWeek;
по заданию у класса Airline есть не день недели (1шт.), а дни недели (много)

2020-08-27 06:40 UTC, alka1ra commented on src/taskAirline/Airline.java
> +    }
"заданный пункт назначения" в данном случае является критерием поиска и, в качестве критерия поиска, не относится к конкретному airline - значит, он должен передаваться извне в метод в качестве параметра

2020-08-27 06:40 UTC, alka1ra commented on src/taskAirline/Airline.java
> +    }
методы поиска не должны относиться к нестатическим методам класса Airline, потому что они должны работать с массивом объектов класса Airline (см. условие)

2020-08-27 06:40 UTC, alka1ra commented on src/taskAirline/Airline.java
> +        }
заданный день недели и заданное время вылета должны задаваться извне, а не вписаны непосредственно в программный код. ведь мы можем захотеть произвести поиск и по другому дню недели\времени - и вместо изменения переданного параметра в методе main мы должны будем лезть в класс Airline и менять вручную значения дня недели и времени.

2020-08-29 06:55 UTC, AntonShtabnoy requested changes

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/task1/Time.java
> +    //создаём конструктор, получающий часы, минуты, секунды в объекте
Нет конструктора, который принимает время только в секундах

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/task1/Time.java
> +}
Неверно реализован метод - он сравнивает ссылки, а не содержимое объектов

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/task1/Time.java
> +    }
лучше назвать getInSeconds() и лучше сделать чтобы метод что-то возвращал, а не просто выводил на экран

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/task1/Time.java
> +        if (sec <= 60 && min <= 60 && hours <= 24) {
Данная проверка не нужна, если корректно реализован конструктор и set - т.е данные проверки нужны в выше перечисленных местах

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/task1/Time.java
> +
Форматирование - не должно быть лишних пробелов

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/task2/Atm.java
> +    }
Отрицательное кол-во купюр может быть?

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/task2/Atm.java
> +    }
вы добавили денег, но если после этого я вызову метод  getNumberOfNotes100() значение этого поля останется таким же. Добавить деньги - значить обновить поля класса

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/task2/Atm.java
> +    }
это не нужно делать полем класса, оно ни как не описывает банкомат, это просто входной параметр в методе

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/task2/Atm.java
> +    }
Не вижу демострации работы данного класса, первый метод где-то используется? 68 и 60 строчки - повторяются. Это плохая практика - все общее нужно выносить в методы

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/task3/Circle.java
> +        Circle circleRunner = new Circle(10);
Ошибка - нужно создавать объект через interface  Shape - объяснение было в видео

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/taskAirline/Airline.java
> +    public String daysOfWeek;
неверный модификатор доступа поля класса, вы кому угодно открыли к ним доступ

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/taskAirline/Airline.java
> +    public String daysOfWeek;
Самолет может летать несколько раз в неделю в одно и тоже время, лучше сделать поле массивом

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/taskAirline/Airline.java
> +    }
На вход должен подаваться массив Airlines и место назначения. Также данные методы поиска лучше вынести в отдельный класс AirlineService

2020-08-29 06:55 UTC, AntonShtabnoy commented on src/taskAirline/Airline.java
> +    public double departureTime;
не очень удачный формат(double) для времени - лучше было использовать наш класс Time из пред урока

2020-09-17 21:26 UTC, AntonShtabnoy requested changes

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskPalindrome/WordPalindrome.java
> +package taskPalindrome;
неверное название пакета - см. литературу по конвенции имен

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskPalindrome/WordPalindrome.java
> +        }
string - это массив char - можно использовать метод chatAt()

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskPalindrome/WordPalindrome.java
> +        }
чтобы вывести просто слово - можно просто написать System.out.println(word)

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskPalindrome/WordPalindrome.java
> +        String word = new String("шалаш"); //введите слово
Лучше создавать строку через кавычки  - без new String(. На уроке обсуждали  - что ваш способ создания создает каждый раз новый объект

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskPalindrome/WordPalindrome.java
> +        }
должен быть метод - который принимает две строки и возвращает true или false

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskLongestString/TheLongestString.java
> +            }
Логика верная - только вынести в отдельный метод, чтобы можно было переиспользовать

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskIP/isIPaString.java
> +public class isIPaString {
см. литературу по названию классов. Классы должны называться с большой буквы

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskIP/isIPaString.java
> +package taskIP;
название пакета

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskByaka/Censor.java
> +public class Censor {
название класса ничего не говорит, что делает класс

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskByaka/Censor.java
> +        System.out.println(str3);
на выходе получу строку в нижнем регистре. А должен получить исходную с замененными словами

2020-09-17 21:26 UTC, AntonShtabnoy commented on src/taskByaka/Censor.java
> +        System.out.println(str3);
Вынести также в отдельный метод с аргументами: строка, слова которое заменяем, на что заменяем

2020-10-04 20:07 UTC, closed without merging